spec-version: 0.36.0 # Avoid legacy Hpack behaviour.

name: time-hourglass
version: 0.2.14
synopsis: A simple and efficient time library
description: |
  A simple and efficient time library.

  A key part of the library is the `Timeable` and `Time` type classes.

  Types representing time values that are instances of the classes allow easy
  conversion between values of one time type and another.
copyright: Vincent Hanquez <vincent@snarc.org>
author: Vincent Hanquez <vincent@snarc.org>
maintainer: Mike Pilgrem <public@pilgrem.com>
category: Time
stability: experimental
homepage: https://github.com/mpilgrem/time-hourglass
github: mpilgrem/time-hourglass
extra-source-files:
- CHANGELOG.md
- README.md
- examples/Example/Time/Compat.hs
- tests/TimeDB.hs

dependencies:
- base >= 4.11 && < 5
- deepseq

ghc-options:
- -Wall

library:
  source-dirs: src
  exposed-modules:
  - Data.Hourglass
  - Data.Hourglass.Compat
  - Data.Hourglass.Epoch
  - Data.Hourglass.Types
  - System.Hourglass
  - Time.Compat
  - Time.Epoch
  - Time.System
  - Time.Types
  when:
  - condition: os(windows)
    then:
      source-dirs: src/win
      dependencies: Win32
    else:
      source-dirs: src/unix
      c-sources: cbits/unix.c

tests:
  test-hourglass:
    source-dirs: tests
    main: Tests.hs
    other-modules:
    - TimeDB
    dependencies:
    - tasty
    - tasty-quickcheck
    - tasty-hunit
    - time-hourglass
    # To test against some other references:
    - time
    when:
    - condition: os(windows)
      then:
        source-dirs: tests/win
      else:
        source-dirs: tests/unix

benchmarks:
  bench-hourglass:
    source-dirs: benchmarks
    main: Bench.hs
    dependencies:
    - time-hourglass
    - tasty-bench
    # To benchmark against other references:
    - time
