spec-version: 0.36.0 # Avoid legacy Hpack behaviour.

name: time-hourglass
version: 0.2.13
synopsis: simple performant time related library
description: |
  Simple time library focusing on simple but powerful and performant API

  The backbone of the library are the Timeable and Time type classes.

  Each Timeable instances can be converted to type that has a Time instances,
  and thus are different representations of current time.
copyright: Vincent Hanquez <vincent@snarc.org>
author: Vincent Hanquez <vincent@snarc.org>
maintainer: Mike Pilgrem <public@pilgrem.com>
category: Time
stability: experimental
homepage: https://github.com/mpilgrem/time-hourglass
github: mpilgrem/time-hourglass
extra-source-files:
- CHANGELOG.md
- README.md
- examples/Example/Time/Compat.hs
- tests/TimeDB.hs

dependencies:
- base >= 4.11 && < 5
- deepseq

ghc-options:
- -Wall

library:
  source-dirs: src
  exposed-modules:
  - Time.Types
  - Time.System
  - Time.Compat
  - Data.Hourglass
  - Data.Hourglass.Types
  - Data.Hourglass.Epoch
  - Data.Hourglass.Compat
  - System.Hourglass
  when:
  - condition: os(windows)
    then:
      source-dirs: src/win
      dependencies: Win32
    else:
      source-dirs: src/unix
      c-sources: cbits/unix.c

tests:
  test-hourglass:
    source-dirs: tests
    main: Tests.hs
    other-modules:
    - TimeDB
    dependencies:
    - tasty
    - tasty-quickcheck
    - tasty-hunit
    - hourglass
    # To test against some other references:
    - time
    when:
    - condition: os(windows)
      then:
        source-dirs: tests/win
      else:
        source-dirs: tests/unix

benchmarks:
  bench-hourglass:
    source-dirs: benchmarks
    main: Bench.hs
    dependencies:
    - hourglass
    - tasty-bench
    # To benchmark against other references:
    - time
